# Generated by Django 6.0.7 on 2026-08-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coding", "0001_initial"),
        ("employees", "0001_initial"),
        ("tools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="coding_skills",
            field=models.ManyToManyField(
                blank=True, related_name="employees", to="coding.coding"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="professional_summary",
            field=models.TextField(blank=True, help_text="Line-separated pointers"),
        ),
        migrations.AddField(
            model_name="employee",
            name="tools",
            field=models.ManyToManyField(
                blank=True, related_name="employees", to="tools.tool"
            ),
        ),
    ]
