# Generated by Django 6.0.7 on 2026-08-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coding", "0001_initial"),
        ("projects", "0001_initial"),
        ("tools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="coding_skills",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="coding.coding"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="role_responsibilities",
            field=models.TextField(blank=True, help_text="Line-separated pointers"),
        ),
        migrations.AddField(
            model_name="project",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="tools",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="tools.tool"
            ),
        ),
    ]
